package com.xworkz.isarelation.Runner;

import com.sun.org.apache.xpath.internal.operations.Or;
import com.xworkz.isarelation.Internal.*;
import sun.security.provider.Sun;

public class MainRunner {
    public static void main(String[] args) {

        System.out.println("1===========================");
        Footwear footwear = new Footwear();
        footwear.wear();
        footwear.run();
        footwear.tie();
        footwear.remove();
        footwear.walk();
        Footwear footwear1 = new Shoe();
        footwear1.wear();
        footwear1.run();
        footwear1.tie();
        footwear1.remove();
        footwear1.walk();
        Shoe shoe = new Shoe();
        shoe.wear();
        shoe.run();
        shoe.tie();
        shoe.remove();
        shoe.walk();
        System.out.println("2==========================================");
        Orange orange = new Orange();
        orange.apply();
        orange.brush();
        orange.fill();
        orange.mix();
        orange.type();
        Orange orange1 = new Color();
        orange1.apply();
        orange1.brush();
        orange1.fill();
        orange1.mix();
        orange1.type();
        Color color = new Color();
        color.apply();
        color.fill();
        color.brush();
        color.mix();
        color.type();
        System.out.println("3==========================");
        Device device = new Device();
        device.brightness();
        device.off();
        device.on();
        device.display();
        device.watch();
        Device device1 = new TV();
        device1.brightness();
        device1.off();
        device1.on();
        device1.display();
        device1.watch();
        TV tv = new TV();
        tv.brightness();
        tv.off();
        tv.on();
        tv.display();
        tv.watch();
        System.out.println("4=================================");
        Mobile mobile = new Mobile();
        mobile.draw();
        mobile.note();
        mobile.play();
        mobile.volumeUp();
        mobile.volumeDown();
        Mobile mobile1 = new Iphone();
        mobile1.draw();
        mobile1.note();
        mobile1.play();
        mobile1.volumeUp();
        mobile1.volumeDown();
        Iphone iphone = new Iphone();
        iphone.draw();
        iphone.note();
        iphone.play();
        iphone.volumeUp();
        iphone.volumeDown();
        System.out.println("5=============================");
        Sport sport = new Sport();
        sport.foul();
        sport.goal();
        sport.kick();
        sport.penalty();
        sport.play();
        Sport sport1 = new Football();
        sport1.foul();
        sport1.goal();
        sport1.kick();
        sport1.penalty();
        sport1.play();
        Football football = new Football();
        football.foul();
        football.goal();
        football.kick();
        football.penalty();
        football.play();
        System.out.println("6======================");
        Document document = new Document();
        document.edit();
        document.print();
        document.delete();
        document.write();
        document.read();
        Document document1 = new Report();
        document1.edit();
        document1.print();
        document1.delete();
        document1.write();
        document1.read();
        Report report = new Report();
        report.edit();
        report.print();
        report.delete();
        report.write();
        report.read();
        System.out.println("7===================================");
        Company company = new Company();
        company.location();
        company.revenue();
        company.sector();
        company.salary();
        company.type();
        Company company1 = new Google();
        company1.location();
        company1.revenue();
        company1.sector();
        company1.salary();
        company1.type();
        Google google = new Google();
        google.location();
        google.sector();
        google.revenue();
        google.salary();
        google.type();
        System.out.println("8===============================");
        Device device2 = new Device();
        device2.brightness();
        device2.off();
        device2.on();
        device2.display();
        device2.watch();
        Device device3 = new TV();
        device3.brightness();
        device3.off();
        device3.on();
        device3.display();
        device3.watch();
        Laptop laptop = new Laptop();
        laptop.brightness();
        laptop.off();
        laptop.on();
        laptop.display();
        laptop.watch();
        System.out.println("9=============================================");
        Sport sport2 = new Sport();
        sport2.foul();
        sport2.goal();
        sport2.kick();
        sport2.penalty();
        sport2.play();
        Sport sport3 = new Football();
        sport3.foul();
        sport3.goal();
        sport3.kick();
        sport3.penalty();
        Hockey hockey = new Hockey();
        hockey.foul();
        hockey.goal();
        hockey.kick();
        hockey.penalty();
        hockey.play();
        System.out.println("10=======================================");
        Mobile mobile2 = new Mobile();
        mobile2.draw();
        mobile2.note();
        mobile2.play();
        mobile2.volumeUp();
        mobile2.volumeDown();
        Mobile mobile3 = new Iphone();
        mobile3.draw();
        mobile3.note();
        mobile3.play();
        mobile3.volumeUp();
        mobile3.volumeDown();
        Samsung samsung = new Samsung();
        samsung.draw();
        samsung.note();
        samsung.play();
        samsung.volumeUp();
        samsung.volumeDown();
        System.out.println("11===================================");
        Mobile mobile4 = new Mobile();
        mobile4.draw();
        mobile4.note();
        mobile4.play();
        mobile4.volumeUp();
        mobile4.volumeDown();
        Mobile mobile5 = new Iphone();
        mobile5.draw();
        mobile5.note();
        mobile5.play();
        mobile5.volumeUp();
        mobile5.volumeDown();
        Oppo oppo = new Oppo();
        oppo.draw();
        oppo.note();
        oppo.play();
        oppo.volumeUp();
        oppo.volumeDown();
        System.out.println("12=================================");
        Sport sport4 = new Sport();
        sport4.foul();
        sport4.goal();
        sport4.kick();
        sport4.penalty();
        sport4.play();
        Sport sport5 = new Football();
        sport5.foul();
        sport5.goal();
        sport5.kick();
        sport5.penalty();
        sport5.play();
        Cricket cricket = new Cricket();
        cricket.foul();
        cricket.goal();
        cricket.kick();
        cricket.penalty();
        cricket.play();
        System.out.println("13=========================================");
        Device device4 = new Device();
        device4.brightness();
        device4.off();
        device4.on();
        device4.display();
        device4.watch();
        Device device5 = new TV();
        device5.brightness();
        device5.off();
        device5.on();
        device5.display();
        device5.watch();
        Speaker speaker = new Speaker();
        speaker.brightness();
        speaker.off();
        speaker.on();
        speaker.display();
        speaker.watch();
        System.out.println("14===================================");
        Footwear footwear2 = new Footwear();
        footwear2.wear();
        footwear2.run();
        footwear2.tie();
        footwear2.remove();
        footwear2.walk();
        Footwear footwear3 = new Shoe();
        footwear3.wear();
        footwear3.run();
        footwear3.tie();
        footwear3.remove();
        footwear3.walk();
        Chappal chappal = new Chappal();
        chappal.wear();
        chappal.run();
        chappal.tie();
        chappal.remove();
        chappal.walk();
        System.out.println("15===========================");
        Mobile mobile6 = new Mobile();
        mobile6.draw();
        mobile6.note();
        mobile6.play();
        mobile6.volumeUp();
        mobile6.volumeDown();
        Mobile mobile7 = new Iphone();
        mobile7.draw();
        mobile7.note();
        mobile7.play();
        mobile7.volumeUp();
        mobile7.volumeDown();
        Poco poco = new Poco();
        poco.draw();
        poco.note();
        poco.play();
        poco.volumeUp();
        poco.volumeDown();
        System.out.println("16===========================");
        Vehicle vehicle = new Vehicle();
        vehicle.start();
        vehicle.stop();
        vehicle.accelerate();
        vehicle.brake();
        Vehicle vehicle1 = new Car();
        vehicle1.start();
        vehicle1.stop();
        vehicle1.accelerate();
        vehicle1.brake();
        Car car = new Car();
        car.start();
        car.stop();
        car.accelerate();
        car.brake();
        System.out.println("17===========================");
        Instrument instrument = new Instrument();
        instrument.play();
        instrument.tune();
        instrument.stop();
        instrument.adjustVolume();
        instrument.repair();
        Instrument instrument1 = new Guitar();
        instrument1.play();
        instrument1.tune();
        instrument1.stop();
        instrument1.adjustVolume();
        instrument1.repair();
        Guitar guitar = new Guitar();
        guitar.play();
        guitar.tune();
        guitar.stop();
        guitar.adjustVolume();
        guitar.repair();
        System.out.println("18======================================");
        Building building = new Building();
        building.openDoors();
        building.closeDoors();
        building.maintenance();
        building.turnOnLights();
        building.turnOffLights();
        Building building1 = new House();
        building1.openDoors();
        building1.closeDoors();
        building1.maintenance();
        building1.turnOnLights();
        building1.turnOffLights();
        House house = new House();
        house.openDoors();
        house.closeDoors();
        house.maintenance();
        house.turnOnLights();
        house.turnOffLights();
        System.out.println("19===================================");
        Animal animal = new Animal();
        animal.eat();
        animal.sleep();
        animal.makeSound();
        animal.run();
        animal.breathe();
        Animal animal1 = new Dog();
        animal1.eat();
        animal1.sleep();
        animal1.makeSound();
        animal1.run();
        animal1.breathe();
        Dog dog = new Dog();
        dog.eat();
        dog.sleep();
        dog.makeSound();
        dog.run();
        dog.breathe();
        System.out.println("20====================================");
        Animal animal2 = new Animal();
        animal2.eat();
        animal2.sleep();
        animal2.makeSound();
        animal2.run();
        animal2.breathe();
        Animal animal3 = new Cat();
        animal3.eat();
        animal3.sleep();
        animal3.makeSound();
        animal3.run();
        animal3.breathe();
        Cat cat = new Cat();
        cat.eat();
        cat.sleep();
        cat.makeSound();
        cat.run();
        cat.breathe();
        System.out.println("21=============================");
        Animal animal4 = new Animal();
        animal4.eat();
        animal4.sleep();
        animal4.makeSound();
        animal4.run();
        animal4.breathe();
        Animal animal5 = new Lion();
        animal5.eat();
        animal5.sleep();
        animal5.makeSound();
        animal5.run();
        animal5.breathe();
        Lion lion = new Lion();
        lion.eat();
        lion.sleep();
        lion.makeSound();
        lion.run();
        lion.breathe();
        System.out.println("22========================================");
        Animal animal6 = new Animal();
        animal6.eat();
        animal6.sleep();
        animal6.makeSound();
        animal6.run();
        animal6.breathe();
        Animal animal7 = new Rabbit();
        animal7.eat();
        animal7.sleep();
        animal7.makeSound();
        animal7.run();
        animal7.breathe();
        Rabbit rabbit = new Rabbit();
        rabbit.eat();
        rabbit.sleep();
        rabbit.makeSound();
        rabbit.run();
        rabbit.breathe();
        System.out.println("23================================");
        Bird bird = new Bird();
        bird.fly();
        bird.chirp();
        bird.nest();
        bird.eat();
        bird.sleep();
        Bird bird1 = new Parrot();
        bird1.fly();
        bird1.chirp();
        bird1.nest();
        bird1.eat();
        bird1.sleep();
        Parrot parrot = new Parrot();
        parrot.fly();
        parrot.chirp();
        parrot.nest();
        parrot.eat();
        parrot.sleep();
        System.out.println("24=============================");
        Bird bird2 = new Bird();
        bird2.fly();
        bird2.chirp();
        bird2.nest();
        bird2.eat();
        bird2.sleep();
        Bird bird3 = new Duck();
        bird3.fly();
        bird3.chirp();
        bird3.nest();
        bird3.eat();
        bird3.sleep();
        Duck duck = new Duck();
        duck.fly();
        duck.chirp();
        duck.nest();
        duck.eat();
        duck.sleep();
        System.out.println("25==========================");
        Bird bird4 = new Bird();
        bird4.fly();
        bird4.chirp();
        bird4.nest();
        bird4.eat();
        bird4.sleep();
        Bird bird5 = new Dove();
        bird5.fly();
        bird5.chirp();
        bird5.nest();
        bird5.eat();
        bird5.sleep();
        Dove dove = new Dove();
        dove.fly();
        dove.chirp();
        dove.nest();
        dove.eat();
        dove.sleep();
        System.out.println("26======================");
        Bird bird6 = new Bird();
        bird6.fly();
        bird6.chirp();
        bird6.nest();
        bird6.eat();
        bird6.sleep();
        Bird bird7 = new Sparrow();
        bird7.fly();
        bird7.chirp();
        bird7.nest();
        bird7.eat();
        bird7.sleep();
        Sparrow sparrow = new Sparrow();
        sparrow.fly();
        sparrow.chirp();
        sparrow.nest();
        sparrow.eat();
        sparrow.sleep();
        System.out.println("27==========================");
        Bird bird8 = new Bird();
        bird8.fly();
        bird8.chirp();
        bird8.nest();
        bird8.eat();
        bird8.sleep();
        Bird bird9 = new Falcon();
        bird9.fly();
        bird9.chirp();
        bird9.nest();
        bird9.eat();
        bird9.sleep();
        Falcon falcon = new Falcon();
        falcon.fly();
        falcon.chirp();
        falcon.nest();
        falcon.eat();
        falcon.sleep();
        System.out.println("28==========================");
        Bird bird10 = new Bird();
        bird10.fly();
        bird10.chirp();
        bird10.nest();
        bird10.eat();
        bird10.sleep();
        Bird bird11 = new Parrot();
        bird11.fly();
        bird11.chirp();
        bird11.nest();
        bird11.eat();
        bird11.sleep();
        Eagle eagle = new Eagle();
        eagle.fly();
        eagle.chirp();
        eagle.nest();
        eagle.eat();
        parrot.sleep();
        System.out.println("29==========================");
        Shape shape = new Shape();
        shape.draw();
        shape.erase();
        shape.resize();
        shape.fill();
        shape.move();
        Shape shape1 = new Circle();
        shape1.draw();
        shape1.erase();
        shape1.resize();
        shape1.fill();
        shape1.move();
        Circle circle = new Circle();
        circle.draw();
        circle.erase();
        circle.resize();
        circle.fill();
        circle.move();
        System.out.println("30==========================");
        Shape shape2 = new Shape();
        shape2.draw();
        shape2.erase();
        shape2.resize();
        shape2.fill();
        shape2.move();
        Shape shape3 = new Square();
        shape3.draw();
        shape3.erase();
        shape3.resize();
        shape3.fill();
        shape3.move();
        Square square=new Square();
        square.draw();
        square.erase();
        square.resize();
        square.fill();
        square.move();
        System.out.println("31==========================");
        Shape shape4 = new Shape();
        shape4.draw();
        shape4.erase();
        shape4.resize();
        shape4.fill();
        shape4.move();
        Shape shape5 = new Rectangle();
        shape5.draw();
        shape5.erase();
        shape5.resize();
        shape5.fill();
        shape5.move();
        Rectangle rectangle=new Rectangle();
        rectangle.draw();
        rectangle.erase();
        rectangle.resize();
        rectangle.fill();
        rectangle.move();
        System.out.println("32==========================");
        Shape shape6 = new Shape();
        shape6.draw();
        shape6.erase();
        shape6.resize();
        shape6.fill();
        shape6.move();
        Shape shape7 = new Traingle();
        shape7.draw();
        shape7.erase();
        shape7.resize();
        shape7.fill();
        shape7.move();
        Traingle traingle=new Traingle();
        traingle.draw();
        traingle.erase();
        traingle.resize();
        traingle.fill();
        traingle.move();
        System.out.println("33==========================");
        Shape shape8 = new Shape();
        shape8.draw();
        shape8.erase();
        shape8.resize();
        shape8.fill();
        shape8.move();
        Shape shape9 = new Pentagon();
        shape9.draw();
        shape9.erase();
        shape9.resize();
        shape9.fill();
        shape9.move();
        Pentagon pentagon=new Pentagon();
        pentagon.draw();
        pentagon.erase();
        pentagon.resize();
        pentagon.fill();
        pentagon.move();
        System.out.println("34============================");
        Festival festival = new Festival();
        festival.celebrate();
        festival.decorate();
        festival.feast();
        festival.enjoyMusic();
        festival.gatherPeople();
        Festival festival1 = new Diwali();
        festival1.celebrate();
        festival1.decorate();
        festival1.feast();
        festival1.enjoyMusic();
        festival1.gatherPeople();
        Diwali diwali = new Diwali();
        diwali.celebrate();
        diwali.decorate();
        diwali.feast();
        diwali.enjoyMusic();
        diwali.gatherPeople();
        System.out.println("35============================");
        Festival festival3 = new Festival();
        festival3.celebrate();
        festival3.decorate();
        festival3.feast();
        festival3.enjoyMusic();
        festival3.gatherPeople();
        Festival festival4 = new Holi();
        festival4.celebrate();
        festival4.decorate();
        festival4.feast();
        festival4.enjoyMusic();
        festival4.gatherPeople();
        Holi holi=new Holi();
        holi.celebrate();
        holi.decorate();
        holi.feast();
        holi.enjoyMusic();
        holi.gatherPeople();
        System.out.println("36============================");
        Festival festival5 = new Festival();
        festival5.celebrate();
        festival5.decorate();
        festival5.feast();
        festival5.enjoyMusic();
        festival5.gatherPeople();
        Festival festival6 = new Ugadi();
        festival6.celebrate();
        festival6.decorate();
        festival6.feast();
        festival6.enjoyMusic();
        festival6.gatherPeople();
        Ugadi ugadi=new Ugadi();
        ugadi.celebrate();
        ugadi.decorate();
        ugadi.feast();
        ugadi.enjoyMusic();
        ugadi.gatherPeople();
        System.out.println("37============================");
        Festival festival7 = new Festival();
        festival7.celebrate();
        festival7.decorate();
        festival7.feast();
        festival7.enjoyMusic();
        festival7.gatherPeople();
        Festival festival8 = new Vishu();
        festival8.celebrate();
        festival8.decorate();
        festival8.feast();
        festival8.enjoyMusic();
        festival8.gatherPeople();
        Vishu vishu=new Vishu();
        vishu.celebrate();
        vishu.decorate();
        vishu.feast();
        vishu.enjoyMusic();
        vishu.gatherPeople();
        System.out.println("38============================");
        Festival festival9 = new Festival();
        festival9.celebrate();
        festival9.decorate();
        festival9.feast();
        festival9.enjoyMusic();
        festival9.gatherPeople();
        Festival festival10 = new Sankranti();
        festival10.celebrate();
        festival10.decorate();
        festival10.feast();
        festival10.enjoyMusic();
        festival10.gatherPeople();
        Sankranti sankranti=new Sankranti();
        sankranti.celebrate();
        sankranti.decorate();
        sankranti.feast();
        sankranti.enjoyMusic();
        sankranti.gatherPeople();
        System.out.println("39=====================");
        Shampoo shampoo=new Shampoo();
        shampoo.apply();
        shampoo.clean();
        shampoo.rub();
        shampoo.rinse();
        shampoo.wash();
        Shampoo shampoo1=new Medimix();
        shampoo1.apply();
        shampoo1.clean();
        shampoo1.rub();
        shampoo1.rinse();
        shampoo1.wash();
        Medimix medimix=new Medimix();
        medimix.apply();
        medimix.clean();
        medimix.rub();
        medimix.rinse();
        medimix.wash();
        System.out.println("40=====================");
        Shampoo shampoo2=new Shampoo();
        shampoo2.apply();
        shampoo2.clean();
        shampoo2.rub();
        shampoo2.rinse();
        shampoo2.wash();
        Shampoo shampoo3=new Clinic();
        shampoo3.apply();
        shampoo3.clean();
        shampoo3.rub();
        shampoo3.rinse();
        shampoo3.wash();
        Clinic clinic=new Clinic();
        clinic.apply();
        clinic.clean();
        clinic.rub();
        clinic.rinse();
        clinic.wash();
        System.out.println("41=====================");
        Shampoo shampoo4=new Shampoo();
        shampoo4.apply();
        shampoo4.clean();
        shampoo4.rub();
        shampoo4.rinse();
        shampoo4.wash();
        Shampoo shampoo5=new Pantene();
        shampoo5.apply();
        shampoo5.clean();
        shampoo5.rub();
        shampoo5.rinse();
        shampoo5.wash();
        Pantene pantene=new Pantene();
        pantene.apply();
        pantene.clean();
        pantene.rub();
        pantene.rinse();
        pantene.wash();
        System.out.println("42=====================");
        Shampoo shampoo6=new Shampoo();
        shampoo6.apply();
        shampoo6.clean();
        shampoo6.rub();
        shampoo6.rinse();
        shampoo6.wash();
        Shampoo shampoo7=new Karthika();
        shampoo7.apply();
        shampoo7.clean();
        shampoo7.rub();
        shampoo7.rinse();
        shampoo7.wash();
        Karthika karthika=new Karthika();
        karthika.apply();
        karthika.clean();
        karthika.rub();
        karthika.rinse();
        karthika.wash();
        System.out.println("42=====================");
        Shampoo shampoo8=new Shampoo();
        shampoo8.apply();
        shampoo8.clean();
        shampoo8.rub();
        shampoo8.rinse();
        shampoo8.wash();
        Shampoo shampoo9=new Sunsilk();
        shampoo9.apply();
        shampoo9.clean();
        shampoo9.rub();
        shampoo9.rinse();
        shampoo9.wash();
        Sunsilk sunsilk=new Sunsilk();
        sunsilk.apply();
        sunsilk.clean();
        sunsilk.rub();
        sunsilk.rinse();
        sunsilk.wash();
        System.out.println("43============================");
        Fruit fruit=new Fruit();
        fruit.cut();
        fruit.smell();
        fruit.eat();
        fruit.fresh();
        fruit.juice();
        Fruit fruit1=new Apple();
        fruit1.cut();
        fruit1.smell();
        fruit1.eat();
        fruit1.fresh();
        fruit1.juice();
        Apple apple=new Apple();
        apple.cut();
        apple.smell();
        apple.eat();
        apple.fresh();
        apple.juice();
        System.out.println("44============================");
        Fruit fruit2=new Fruit();
        fruit2.cut();
        fruit2.smell();
        fruit2.eat();
        fruit2.fresh();
        fruit2.juice();
        Fruit fruit3=new Mango();
        fruit3.cut();
        fruit3.smell();
        fruit3.eat();
        fruit3.fresh();
        fruit3.juice();
        Mango mango=new Mango();
        mango.cut();
        mango.smell();
        mango.eat();
        mango.fresh();
        mango.juice();
        System.out.println("45============================");
        Fruit fruit4=new Fruit();
        fruit4.cut();
        fruit4.smell();
        fruit4.eat();
        fruit4.fresh();
        fruit4.juice();
        Fruit fruit5=new Chikku();
        fruit5.cut();
        fruit5.smell();
        fruit5.eat();
        fruit5.fresh();
        fruit5.juice();
        Chikku chikku=new Chikku();
        chikku.cut();
        chikku.smell();
        chikku.eat();
        chikku.fresh();
        chikku.juice();
        System.out.println("46============================");
        Fruit fruit6=new Fruit();
        fruit6.cut();
        fruit6.smell();
        fruit6.eat();
        fruit6.fresh();
        fruit6.juice();
        Fruit fruit7=new Musambi();
        fruit7.cut();
        fruit7.smell();
        fruit7.eat();
        fruit7.fresh();
        fruit5.juice();
        Musambi musambi=new Musambi();
        musambi.cut();
        musambi.smell();
        musambi.eat();
        musambi.fresh();
        musambi.juice();
        System.out.println("47============================");
        Fruit fruit8=new Fruit();
        fruit8.cut();
        fruit8.smell();
        fruit8.eat();
        fruit8.fresh();
        fruit8.juice();
        Fruit fruit9=new Grapes();
        fruit9.cut();
        fruit9.smell();
        fruit9.eat();
        fruit9.fresh();
        fruit9.juice();
        Grapes grapes=new Grapes();
        grapes.cut();
        grapes.smell();
        grapes.eat();
        grapes.fresh();
        grapes.juice();
        System.out.println("48============================");
        Fruit fruit10=new Fruit();
        fruit10.cut();
        fruit10.smell();
        fruit10.eat();
        fruit10.fresh();
        fruit10.juice();
        Fruit fruit11=new Watermelon();
        fruit11.cut();
        fruit11.smell();
        fruit11.eat();
        fruit11.fresh();
        fruit11.juice();
        Watermelon watermelon=new Watermelon();
        grapes.cut();
        grapes.smell();
        grapes.eat();
        grapes.fresh();
        grapes.juice();
        System.out.println("49============================");
        Fruit fruit12=new Fruit();
        fruit12.cut();
        fruit12.smell();
        fruit12.eat();
        fruit12.fresh();
        fruit12.juice();
        Fruit fruit13=new Kiwi();
        fruit13.cut();
        fruit13.smell();
        fruit13.eat();
        fruit13.fresh();
        fruit13.juice();
        Kiwi kiwi=new Kiwi();
        kiwi.cut();
        kiwi.smell();
        kiwi.eat();
        kiwi.fresh();
        kiwi.juice();







    }
}
