package com.xworkz.isarelation.Runner;

import com.xworkz.isarelation.Internal.*;

public class MainRunner {
    public static void main(String[] args) {

        System.out.println("1===========================");
        Footwear footwear = new Footwear();
        footwear.wear();
        footwear.run();
        footwear.tie();
        footwear.remove();
        footwear.walk();
        Footwear footwear1 = new Shoe();
        footwear1.wear();
        footwear1.run();
        footwear1.tie();
        footwear1.remove();
        footwear1.walk();
        Shoe shoe = new Shoe();
        shoe.wear();
        shoe.run();
        shoe.tie();
        shoe.remove();
        shoe.walk();
        System.out.println("2==========================================");
        Orange orange = new Orange();
        orange.apply();
        orange.brush();
        orange.fill();
        orange.mix();
        orange.type();
        Orange orange1 = new Color();
        orange1.apply();
        orange1.brush();
        orange1.fill();
        orange1.mix();
        orange1.type();
        Color color = new Color();
        color.apply();
        color.fill();
        color.brush();
        color.mix();
        color.type();
        System.out.println("3==========================");
        Device device = new Device();
        device.brightness();
        device.off();
        device.on();
        device.display();
        device.watch();
        Device device1 = new TV();
        device1.brightness();
        device1.off();
        device1.on();
        device1.display();
        device1.watch();
        TV tv = new TV();
        tv.brightness();
        tv.off();
        tv.on();
        tv.display();
        tv.watch();
        System.out.println("4=================================");
        Mobile mobile = new Mobile();
        mobile.draw();
        mobile.note();
        mobile.play();
        mobile.volumeUp();
        mobile.volumeDown();
        Mobile mobile1 = new Iphone();
        mobile1.draw();
        mobile1.note();
        mobile1.play();
        mobile1.volumeUp();
        mobile1.volumeDown();
        Iphone iphone = new Iphone();
        iphone.draw();
        iphone.note();
        iphone.play();
        iphone.volumeUp();
        iphone.volumeDown();
        System.out.println("5=============================");
        Sport sport = new Sport();
        sport.foul();
        sport.goal();
        sport.kick();
        sport.penalty();
        sport.play();
        Sport sport1 = new Football();
        sport1.foul();
        sport1.goal();
        sport1.kick();
        sport1.penalty();
        sport1.play();
        Football football = new Football();
        football.foul();
        football.goal();
        football.kick();
        football.penalty();
        football.play();
        System.out.println("6======================");
        Document document = new Document();
        document.edit();
        document.print();
        document.delete();
        document.write();
        document.read();
        Document document1 = new Report();
        document1.edit();
        document1.print();
        document1.delete();
        document1.write();
        document1.read();
        Report report = new Report();
        report.edit();
        report.print();
        report.delete();
        report.write();
        report.read();
        System.out.println("7===================================");
        Company company = new Company();
        company.location();
        company.revenue();
        company.sector();
        company.salary();
        company.type();
        Company company1 = new Google();
        company1.location();
        company1.revenue();
        company1.sector();
        company1.salary();
        company1.type();
        Google google = new Google();
        google.location();
        google.sector();
        google.revenue();
        google.salary();
        google.type();
        System.out.println("8===============================");
        Device device2 = new Device();
        device2.brightness();
        device2.off();
        device2.on();
        device2.display();
        device2.watch();
        Device device3 = new Laptop();
        device3.brightness();
        device3.off();
        device3.on();
        device3.display();
        device3.watch();
        Laptop laptop = new Laptop();
        laptop.brightness();
        laptop.off();
        laptop.on();
        laptop.display();
        laptop.watch();
        System.out.println("9=============================================");
        Sport sport2 = new Sport();
        sport2.foul();
        sport2.goal();
        sport2.kick();
        sport2.penalty();
        sport2.play();
        Sport sport3 = new Hockey();
        sport3.foul();
        sport3.goal();
        sport3.kick();
        sport3.penalty();
        Hockey hockey = new Hockey();
        hockey.foul();
        hockey.goal();
        hockey.kick();
        hockey.penalty();
        hockey.play();
        System.out.println("10=======================================");
        Mobile mobile2 = new Mobile();
        mobile2.draw();
        mobile2.note();
        mobile2.play();
        mobile2.volumeUp();
        mobile2.volumeDown();
        Mobile mobile3 = new Samsung();
        mobile3.draw();
        mobile3.note();
        mobile3.play();
        mobile3.volumeUp();
        mobile3.volumeDown();
        Samsung samsung = new Samsung();
        samsung.draw();
        samsung.note();
        samsung.play();
        samsung.volumeUp();
        samsung.volumeDown();
        System.out.println("11===================================");
        Mobile mobile4 = new Mobile();
        mobile4.draw();
        mobile4.note();
        mobile4.play();
        mobile4.volumeUp();
        mobile4.volumeDown();
        Mobile mobile5 = new Oppo();
        mobile5.draw();
        mobile5.note();
        mobile5.play();
        mobile5.volumeUp();
        mobile5.volumeDown();
        Oppo oppo = new Oppo();
        oppo.draw();
        oppo.note();
        oppo.play();
        oppo.volumeUp();
        oppo.volumeDown();
        System.out.println("12=================================");
        Sport sport4 = new Sport();
        sport4.foul();
        sport4.goal();
        sport4.kick();
        sport4.penalty();
        sport4.play();
        Sport sport5 = new Cricket();
        sport5.foul();
        sport5.goal();
        sport5.kick();
        sport5.penalty();
        sport5.play();
        Cricket cricket = new Cricket();
        cricket.foul();
        cricket.goal();
        cricket.kick();
        cricket.penalty();
        cricket.play();
        System.out.println("13=========================================");
        Device device4 = new Device();
        device4.brightness();
        device4.off();
        device4.on();
        device4.display();
        device4.watch();
        Device device5 = new Speaker();
        device5.brightness();
        device5.off();
        device5.on();
        device5.display();
        device5.watch();
        Speaker speaker = new Speaker();
        speaker.brightness();
        speaker.off();
        speaker.on();
        speaker.display();
        speaker.watch();
        System.out.println("14===================================");
        Footwear footwear2 = new Footwear();
        footwear2.wear();
        footwear2.run();
        footwear2.tie();
        footwear2.remove();
        footwear2.walk();
        Footwear footwear3 = new Chappal();
        footwear3.wear();
        footwear3.run();
        footwear3.tie();
        footwear3.remove();
        footwear3.walk();
        Chappal chappal = new Chappal();
        chappal.wear();
        chappal.run();
        chappal.tie();
        chappal.remove();
        chappal.walk();
        System.out.println("15===========================");
        Mobile mobile6 = new Mobile();
        mobile6.draw();
        mobile6.note();
        mobile6.play();
        mobile6.volumeUp();
        mobile6.volumeDown();
        Mobile mobile7 = new Poco();
        mobile7.draw();
        mobile7.note();
        mobile7.play();
        mobile7.volumeUp();
        mobile7.volumeDown();
        Poco poco = new Poco();
        poco.draw();
        poco.note();
        poco.play();
        poco.volumeUp();
        poco.volumeDown();
        System.out.println("16===========================");
        Vehicle vehicle = new Vehicle();
        vehicle.start();
        vehicle.stop();
        vehicle.accelerate();
        vehicle.brake();
        Vehicle vehicle1 = new Car();
        vehicle1.start();
        vehicle1.stop();
        vehicle1.accelerate();
        vehicle1.brake();
        Car car = new Car();
        car.start();
        car.stop();
        car.accelerate();
        car.brake();
        System.out.println("17===========================");
        Instrument instrument = new Instrument();
        instrument.play();
        instrument.tune();
        instrument.stop();
        instrument.adjustVolume();
        instrument.repair();
        Instrument instrument1 = new Guitar();
        instrument1.play();
        instrument1.tune();
        instrument1.stop();
        instrument1.adjustVolume();
        instrument1.repair();
        Guitar guitar = new Guitar();
        guitar.play();
        guitar.tune();
        guitar.stop();
        guitar.adjustVolume();
        guitar.repair();
        System.out.println("18======================================");
        Building building = new Building();
        building.openDoors();
        building.closeDoors();
        building.maintenance();
        building.turnOnLights();
        building.turnOffLights();
        Building building1 = new House();
        building1.openDoors();
        building1.closeDoors();
        building1.maintenance();
        building1.turnOnLights();
        building1.turnOffLights();
        House house = new House();
        house.openDoors();
        house.closeDoors();
        house.maintenance();
        house.turnOnLights();
        house.turnOffLights();
        System.out.println("19===================================");
        Animal animal = new Animal();
        animal.eat();
        animal.sleep();
        animal.makeSound();
        animal.run();
        animal.breathe();
        Animal animal1 = new Dog();
        animal1.eat();
        animal1.sleep();
        animal1.makeSound();
        animal1.run();
        animal1.breathe();
        Dog dog = new Dog();
        dog.eat();
        dog.sleep();
        dog.makeSound();
        dog.run();
        dog.breathe();
        System.out.println("20====================================");
        Animal animal2 = new Animal();
        animal2.eat();
        animal2.sleep();
        animal2.makeSound();
        animal2.run();
        animal2.breathe();
        Animal animal3 = new Cat();
        animal3.eat();
        animal3.sleep();
        animal3.makeSound();
        animal3.run();
        animal3.breathe();
        Cat cat = new Cat();
        cat.eat();
        cat.sleep();
        cat.makeSound();
        cat.run();
        cat.breathe();
        System.out.println("21=============================");
        Animal animal4 = new Animal();
        animal4.eat();
        animal4.sleep();
        animal4.makeSound();
        animal4.run();
        animal4.breathe();
        Animal animal5 = new Lion();
        animal5.eat();
        animal5.sleep();
        animal5.makeSound();
        animal5.run();
        animal5.breathe();
        Lion lion = new Lion();
        lion.eat();
        lion.sleep();
        lion.makeSound();
        lion.run();
        lion.breathe();
        System.out.println("22========================================");
        Animal animal6 = new Animal();
        animal6.eat();
        animal6.sleep();
        animal6.makeSound();
        animal6.run();
        animal6.breathe();
        Animal animal7 = new Rabbit();
        animal7.eat();
        animal7.sleep();
        animal7.makeSound();
        animal7.run();
        animal7.breathe();
        Rabbit rabbit = new Rabbit();
        rabbit.eat();
        rabbit.sleep();
        rabbit.makeSound();
        rabbit.run();
        rabbit.breathe();
        System.out.println("23================================");
        Bird bird = new Bird();
        bird.fly();
        bird.chirp();
        bird.nest();
        bird.eat();
        bird.sleep();
        Bird bird1 = new Parrot();
        bird1.fly();
        bird1.chirp();
        bird1.nest();
        bird1.eat();
        bird1.sleep();
        Parrot parrot = new Parrot();
        parrot.fly();
        parrot.chirp();
        parrot.nest();
        parrot.eat();
        parrot.sleep();
        System.out.println("24=============================");
        Bird bird2 = new Bird();
        bird2.fly();
        bird2.chirp();
        bird2.nest();
        bird2.eat();
        bird2.sleep();
        Bird bird3 = new Duck();
        bird3.fly();
        bird3.chirp();
        bird3.nest();
        bird3.eat();
        bird3.sleep();
        Duck duck = new Duck();
        duck.fly();
        duck.chirp();
        duck.nest();
        duck.eat();
        duck.sleep();
        System.out.println("25==========================");
        Bird bird4 = new Bird();
        bird4.fly();
        bird4.chirp();
        bird4.nest();
        bird4.eat();
        bird4.sleep();
        Bird bird5 = new Dove();
        bird5.fly();
        bird5.chirp();
        bird5.nest();
        bird5.eat();
        bird5.sleep();
        Dove dove = new Dove();
        dove.fly();
        dove.chirp();
        dove.nest();
        dove.eat();
        dove.sleep();
        System.out.println("26======================");
        Bird bird6 = new Bird();
        bird6.fly();
        bird6.chirp();
        bird6.nest();
        bird6.eat();
        bird6.sleep();
        Bird bird7 = new Sparrow();
        bird7.fly();
        bird7.chirp();
        bird7.nest();
        bird7.eat();
        bird7.sleep();
        Sparrow sparrow = new Sparrow();
        sparrow.fly();
        sparrow.chirp();
        sparrow.nest();
        sparrow.eat();
        sparrow.sleep();
        System.out.println("27==========================");
        Bird bird8 = new Bird();
        bird8.fly();
        bird8.chirp();
        bird8.nest();
        bird8.eat();
        bird8.sleep();
        Bird bird9 = new Falcon();
        bird9.fly();
        bird9.chirp();
        bird9.nest();
        bird9.eat();
        bird9.sleep();
        Falcon falcon = new Falcon();
        falcon.fly();
        falcon.chirp();
        falcon.nest();
        falcon.eat();
        falcon.sleep();
        System.out.println("28==========================");
        Bird bird10 = new Bird();
        bird10.fly();
        bird10.chirp();
        bird10.nest();
        bird10.eat();
        bird10.sleep();
        Bird bird11 = new Eagle();
        bird11.fly();
        bird11.chirp();
        bird11.nest();
        bird11.eat();
        bird11.sleep();
        Eagle eagle = new Eagle();
        eagle.fly();
        eagle.chirp();
        eagle.nest();
        eagle.eat();
        parrot.sleep();
        System.out.println("29==========================");
        Shape shape = new Shape();
        shape.draw();
        shape.erase();
        shape.resize();
        shape.fill();
        shape.move();
        Shape shape1 = new Circle();
        shape1.draw();
        shape1.erase();
        shape1.resize();
        shape1.fill();
        shape1.move();
        Circle circle = new Circle();
        circle.draw();
        circle.erase();
        circle.resize();
        circle.fill();
        circle.move();
        System.out.println("30==========================");
        Shape shape2 = new Shape();
        shape2.draw();
        shape2.erase();
        shape2.resize();
        shape2.fill();
        shape2.move();
        Shape shape3 = new Square();
        shape3.draw();
        shape3.erase();
        shape3.resize();
        shape3.fill();
        shape3.move();
        Square square = new Square();
        square.draw();
        square.erase();
        square.resize();
        square.fill();
        square.move();
        System.out.println("31==========================");
        Shape shape4 = new Shape();
        shape4.draw();
        shape4.erase();
        shape4.resize();
        shape4.fill();
        shape4.move();
        Shape shape5 = new Rectangle();
        shape5.draw();
        shape5.erase();
        shape5.resize();
        shape5.fill();
        shape5.move();
        Rectangle rectangle = new Rectangle();
        rectangle.draw();
        rectangle.erase();
        rectangle.resize();
        rectangle.fill();
        rectangle.move();
        System.out.println("32==========================");
        Shape shape6 = new Shape();
        shape6.draw();
        shape6.erase();
        shape6.resize();
        shape6.fill();
        shape6.move();
        Shape shape7 = new Traingle();
        shape7.draw();
        shape7.erase();
        shape7.resize();
        shape7.fill();
        shape7.move();
        Traingle traingle = new Traingle();
        traingle.draw();
        traingle.erase();
        traingle.resize();
        traingle.fill();
        traingle.move();
        System.out.println("33==========================");
        Shape shape8 = new Shape();
        shape8.draw();
        shape8.erase();
        shape8.resize();
        shape8.fill();
        shape8.move();
        Shape shape9 = new Pentagon();
        shape9.draw();
        shape9.erase();
        shape9.resize();
        shape9.fill();
        shape9.move();
        Pentagon pentagon = new Pentagon();
        pentagon.draw();
        pentagon.erase();
        pentagon.resize();
        pentagon.fill();
        pentagon.move();
        System.out.println("34============================");
        Festival festival = new Festival();
        festival.celebrate();
        festival.decorate();
        festival.feast();
        festival.enjoyMusic();
        festival.gatherPeople();
        Festival festival1 = new Diwali();
        festival1.celebrate();
        festival1.decorate();
        festival1.feast();
        festival1.enjoyMusic();
        festival1.gatherPeople();
        Diwali diwali = new Diwali();
        diwali.celebrate();
        diwali.decorate();
        diwali.feast();
        diwali.enjoyMusic();
        diwali.gatherPeople();
        System.out.println("35============================");
        Festival festival3 = new Festival();
        festival3.celebrate();
        festival3.decorate();
        festival3.feast();
        festival3.enjoyMusic();
        festival3.gatherPeople();
        Festival festival4 = new Holi();
        festival4.celebrate();
        festival4.decorate();
        festival4.feast();
        festival4.enjoyMusic();
        festival4.gatherPeople();
        Holi holi = new Holi();
        holi.celebrate();
        holi.decorate();
        holi.feast();
        holi.enjoyMusic();
        holi.gatherPeople();
        System.out.println("36============================");
        Festival festival5 = new Festival();
        festival5.celebrate();
        festival5.decorate();
        festival5.feast();
        festival5.enjoyMusic();
        festival5.gatherPeople();
        Festival festival6 = new Ugadi();
        festival6.celebrate();
        festival6.decorate();
        festival6.feast();
        festival6.enjoyMusic();
        festival6.gatherPeople();
        Ugadi ugadi = new Ugadi();
        ugadi.celebrate();
        ugadi.decorate();
        ugadi.feast();
        ugadi.enjoyMusic();
        ugadi.gatherPeople();
        System.out.println("37============================");
        Festival festival7 = new Festival();
        festival7.celebrate();
        festival7.decorate();
        festival7.feast();
        festival7.enjoyMusic();
        festival7.gatherPeople();
        Festival festival8 = new Vishu();
        festival8.celebrate();
        festival8.decorate();
        festival8.feast();
        festival8.enjoyMusic();
        festival8.gatherPeople();
        Vishu vishu = new Vishu();
        vishu.celebrate();
        vishu.decorate();
        vishu.feast();
        vishu.enjoyMusic();
        vishu.gatherPeople();
        System.out.println("38============================");
        Festival festival9 = new Festival();
        festival9.celebrate();
        festival9.decorate();
        festival9.feast();
        festival9.enjoyMusic();
        festival9.gatherPeople();
        Festival festival10 = new Sankranti();
        festival10.celebrate();
        festival10.decorate();
        festival10.feast();
        festival10.enjoyMusic();
        festival10.gatherPeople();
        Sankranti sankranti = new Sankranti();
        sankranti.celebrate();
        sankranti.decorate();
        sankranti.feast();
        sankranti.enjoyMusic();
        sankranti.gatherPeople();
        System.out.println("39=====================");
        Shampoo shampoo = new Shampoo();
        shampoo.apply();
        shampoo.clean();
        shampoo.rub();
        shampoo.rinse();
        shampoo.wash();
        Shampoo shampoo1 = new Medimix();
        shampoo1.apply();
        shampoo1.clean();
        shampoo1.rub();
        shampoo1.rinse();
        shampoo1.wash();
        Medimix medimix = new Medimix();
        medimix.apply();
        medimix.clean();
        medimix.rub();
        medimix.rinse();
        medimix.wash();
        System.out.println("40=====================");
        Shampoo shampoo2 = new Shampoo();
        shampoo2.apply();
        shampoo2.clean();
        shampoo2.rub();
        shampoo2.rinse();
        shampoo2.wash();
        Shampoo shampoo3 = new Clinic();
        shampoo3.apply();
        shampoo3.clean();
        shampoo3.rub();
        shampoo3.rinse();
        shampoo3.wash();
        Clinic clinic = new Clinic();
        clinic.apply();
        clinic.clean();
        clinic.rub();
        clinic.rinse();
        clinic.wash();
        System.out.println("41=====================");
        Shampoo shampoo4 = new Shampoo();
        shampoo4.apply();
        shampoo4.clean();
        shampoo4.rub();
        shampoo4.rinse();
        shampoo4.wash();
        Shampoo shampoo5 = new Pantene();
        shampoo5.apply();
        shampoo5.clean();
        shampoo5.rub();
        shampoo5.rinse();
        shampoo5.wash();
        Pantene pantene = new Pantene();
        pantene.apply();
        pantene.clean();
        pantene.rub();
        pantene.rinse();
        pantene.wash();
        System.out.println("42=====================");
        Shampoo shampoo6 = new Shampoo();
        shampoo6.apply();
        shampoo6.clean();
        shampoo6.rub();
        shampoo6.rinse();
        shampoo6.wash();
        Shampoo shampoo7 = new Karthika();
        shampoo7.apply();
        shampoo7.clean();
        shampoo7.rub();
        shampoo7.rinse();
        shampoo7.wash();
        Karthika karthika = new Karthika();
        karthika.apply();
        karthika.clean();
        karthika.rub();
        karthika.rinse();
        karthika.wash();
        System.out.println("42=====================");
        Shampoo shampoo8 = new Shampoo();
        shampoo8.apply();
        shampoo8.clean();
        shampoo8.rub();
        shampoo8.rinse();
        shampoo8.wash();
        Shampoo shampoo9 = new Sunsilk();
        shampoo9.apply();
        shampoo9.clean();
        shampoo9.rub();
        shampoo9.rinse();
        shampoo9.wash();
        Sunsilk sunsilk = new Sunsilk();
        sunsilk.apply();
        sunsilk.clean();
        sunsilk.rub();
        sunsilk.rinse();
        sunsilk.wash();
        System.out.println("43============================");
        Fruit fruit = new Fruit();
        fruit.cut();
        fruit.smell();
        fruit.eat();
        fruit.fresh();
        fruit.juice();
        Fruit fruit1 = new Apple();
        fruit1.cut();
        fruit1.smell();
        fruit1.eat();
        fruit1.fresh();
        fruit1.juice();
        Apple apple = new Apple();
        apple.cut();
        apple.smell();
        apple.eat();
        apple.fresh();
        apple.juice();
        System.out.println("44============================");
        Fruit fruit2 = new Fruit();
        fruit2.cut();
        fruit2.smell();
        fruit2.eat();
        fruit2.fresh();
        fruit2.juice();
        Fruit fruit3 = new Mango();
        fruit3.cut();
        fruit3.smell();
        fruit3.eat();
        fruit3.fresh();
        fruit3.juice();
        Mango mango = new Mango();
        mango.cut();
        mango.smell();
        mango.eat();
        mango.fresh();
        mango.juice();
        System.out.println("45============================");
        Fruit fruit4 = new Fruit();
        fruit4.cut();
        fruit4.smell();
        fruit4.eat();
        fruit4.fresh();
        fruit4.juice();
        Fruit fruit5 = new Chikku();
        fruit5.cut();
        fruit5.smell();
        fruit5.eat();
        fruit5.fresh();
        fruit5.juice();
        Chikku chikku = new Chikku();
        chikku.cut();
        chikku.smell();
        chikku.eat();
        chikku.fresh();
        chikku.juice();
        System.out.println("46============================");
        Fruit fruit6 = new Fruit();
        fruit6.cut();
        fruit6.smell();
        fruit6.eat();
        fruit6.fresh();
        fruit6.juice();
        Fruit fruit7 = new Musambi();
        fruit7.cut();
        fruit7.smell();
        fruit7.eat();
        fruit7.fresh();
        fruit5.juice();
        Musambi musambi = new Musambi();
        musambi.cut();
        musambi.smell();
        musambi.eat();
        musambi.fresh();
        musambi.juice();
        System.out.println("47============================");
        Fruit fruit8 = new Fruit();
        fruit8.cut();
        fruit8.smell();
        fruit8.eat();
        fruit8.fresh();
        fruit8.juice();
        Fruit fruit9 = new Grapes();
        fruit9.cut();
        fruit9.smell();
        fruit9.eat();
        fruit9.fresh();
        fruit9.juice();
        Grapes grapes = new Grapes();
        grapes.cut();
        grapes.smell();
        grapes.eat();
        grapes.fresh();
        grapes.juice();
        System.out.println("48============================");
        Fruit fruit10 = new Fruit();
        fruit10.cut();
        fruit10.smell();
        fruit10.eat();
        fruit10.fresh();
        fruit10.juice();
        Fruit fruit11 = new Watermelon();
        fruit11.cut();
        fruit11.smell();
        fruit11.eat();
        fruit11.fresh();
        fruit11.juice();
        Watermelon watermelon = new Watermelon();
        watermelon.cut();
        watermelon.smell();
        watermelon.eat();
        watermelon.fresh();
        watermelon.juice();
        System.out.println("49============================");
        Fruit fruit12 = new Fruit();
        fruit12.cut();
        fruit12.smell();
        fruit12.eat();
        fruit12.fresh();
        fruit12.juice();
        Fruit fruit13 = new Kiwi();
        fruit13.cut();
        fruit13.smell();
        fruit13.eat();
        fruit13.fresh();
        fruit13.juice();
        Kiwi kiwi = new Kiwi();
        kiwi.cut();
        kiwi.smell();
        kiwi.eat();
        kiwi.fresh();
        kiwi.juice();
        System.out.println("50===============================");
        Fruit fruit14 = new Fruit();
        fruit14.cut();
        fruit14.smell();
        fruit14.eat();
        fruit14.fresh();
        fruit14.juice();
        Fruit fruit15 = new Banana();
        fruit15.cut();
        fruit15.smell();
        fruit15.eat();
        fruit15.fresh();
        fruit15.juice();
        Banana banana = new Banana();
        banana.cut();
        banana.smell();
        banana.eat();
        banana.fresh();
        banana.juice();
        System.out.println("51===============================");
        Vegetable vegetable = new Vegetable();
        vegetable.cook();
        vegetable.chew();
        vegetable.curry();
        vegetable.sell();
        vegetable.steam();
        Vegetable vegetable1 = new Brinjal();
        vegetable1.cook();
        vegetable1.chew();
        vegetable1.curry();
        vegetable1.sell();
        vegetable1.steam();
        Brinjal brinjal = new Brinjal();
        brinjal.cook();
        brinjal.chew();
        brinjal.curry();
        brinjal.sell();
        brinjal.steam();
        System.out.println("52====================");
        Bike bike = new Bike();
        bike.ride();
        bike.clutch();
        bike.drag();
        bike.race();
        bike.tour();
        Bike bike1 = new Splender();
        bike1.ride();
        bike1.clutch();
        bike1.drag();
        bike1.race();
        bike1.tour();
        Splender splender = new Splender();
        splender.ride();
        splender.clutch();
        splender.drag();
        splender.race();
        splender.tour();
        System.out.println("53=======================");
        Bus bus = new Bus();
        bus.ticket();
        bus.pass();
        bus.seat();
        bus.reserved();
        bus.stand();
        Bus bus1 = new BMTC();
        bus1.ticket();
        bus1.pass();
        bus1.seat();
        bus1.reserved();
        bus1.stand();
        BMTC bmtc = new BMTC();
        bmtc.ticket();
        bmtc.pass();
        bmtc.seat();
        bmtc.reserved();
        bmtc.stand();
        System.out.println("54===============================");
        AudioDevice audioDevice = new AudioDevice();
        audioDevice.listen();
        audioDevice.beats();
        audioDevice.music();
        audioDevice.play();
        audioDevice.call();
        AudioDevice audioDevice1 = new Airpods();
        audioDevice1.listen();
        audioDevice1.beats();
        audioDevice1.music();
        audioDevice1.play();
        audioDevice1.call();
        Airpods airpods = new Airpods();
        airpods.listen();
        airpods.beats();
        airpods.music();
        airpods.play();
        airpods.call();
        System.out.println("55========================");
        Furniture furniture = new Furniture();
        furniture.cusion();
        furniture.comfort();
        furniture.pillow();
        furniture.fold();
        furniture.pillow();
        Furniture furniture1 = new Sofa();
        furniture1.cusion();
        furniture1.comfort();
        furniture1.pillow();
        furniture1.fold();
        furniture1.pillow();
        Sofa sofa = new Sofa();
        sofa.cusion();
        sofa.comfort();
        sofa.pillow();
        sofa.fold();
        sofa.pillow();
        System.out.println("56======================");
        Language language = new Language();
        language.learn();
        language.improve();
        language.read();
        language.talk();
        language.write();
        Language language1 = new English();
        language1.learn();
        language1.improve();
        language1.read();
        language1.talk();
        language1.write();
        English english = new English();
        english.learn();
        english.improve();
        english.read();
        english.talk();
        english.write();
        System.out.println("57==============");
        ProgrammingLanguage programmingLanguage = new ProgrammingLanguage();
        programmingLanguage.code();
        programmingLanguage.error();
        programmingLanguage.compile();
        programmingLanguage.run();
        programmingLanguage.debug();
        ProgrammingLanguage programmingLanguage1 = new Java();
        programmingLanguage1.code();
        programmingLanguage1.error();
        programmingLanguage1.compile();
        programmingLanguage1.run();
        programmingLanguage1.debug();
        Java java = new Java();
        java.code();
        java.error();
        java.compile();
        java.run();
        java.debug();
        System.out.println("58=================");
        OutputDevice outputDevice = new OutputDevice();
        outputDevice.output();
        outputDevice.print();
        outputDevice.connect();
        outputDevice.disconnect();
        outputDevice.produce();
        OutputDevice outputDevice1 = new Printer();
        outputDevice1.output();
        outputDevice1.print();
        outputDevice1.connect();
        outputDevice1.disconnect();
        outputDevice1.produce();
        Printer printer = new Printer();
        printer.output();
        printer.print();
        printer.connect();
        printer.disconnect();
        printer.produce();
        System.out.println("59====================");
        Bag bag = new Bag();
        bag.carry();
        bag.zip();
        bag.unzip();
        bag.pouches();
        bag.size();
        Bag bag1 = new SkyBag();
        bag1.carry();
        bag1.zip();
        bag1.unzip();
        bag1.pouches();
        bag1.size();
        SkyBag skyBag = new SkyBag();
        skyBag.carry();
        skyBag.zip();
        skyBag.unzip();
        skyBag.pouches();
        skyBag.size();
        System.out.println("60===========================");
        Employee employee = new Employee();
        employee.work();
        employee.attendMeeting();
        employee.takeBreak();
        employee.submitReport();
        employee.getSalary();
        Employee employee1 = new Manager();
        employee1.work();
        employee1.attendMeeting();
        employee1.takeBreak();
        employee1.submitReport();
        employee1.getSalary();
        Manager manager = new Manager();
        manager.work();
        manager.attendMeeting();
        manager.takeBreak();
        manager.submitReport();
        manager.getSalary();
        System.out.println("61==================");
        Bank bank = new Bank();
        bank.deposit();
        bank.withdraw();
        bank.checkBalance();
        bank.transferMoney();
        bank.provideLoan();
        Bank bank1 = new SavingsAccount();
        bank1.deposit();
        bank1.withdraw();
        bank1.checkBalance();
        bank1.transferMoney();
        bank1.provideLoan();
        SavingsAccount savingsAccount = new SavingsAccount();
        savingsAccount.deposit();
        savingsAccount.withdraw();
        savingsAccount.checkBalance();
        savingsAccount.transferMoney();
        savingsAccount.provideLoan();
        System.out.println("62=======================");
        Teacher teacher = new Teacher();
        teacher.teach();
        teacher.evaluate();
        teacher.assignHomework();
        teacher.conductExam();
        teacher.guideStudents();
        Teacher teacher1 = new MathTeacher();
        teacher1.teach();
        teacher1.evaluate();
        teacher1.assignHomework();
        teacher1.conductExam();
        teacher1.guideStudents();
        MathTeacher mathTeacher = new MathTeacher();
        mathTeacher.teach();
        mathTeacher.evaluate();
        mathTeacher.assignHomework();
        mathTeacher.conductExam();
        mathTeacher.guideStudents();
        System.out.println("63============================");
        Medicine medicine = new Medicine();
        medicine.cure();
        medicine.dosage();
        medicine.store();
        medicine.manufacture();
        medicine.expiryDate();
        Medicine medicine1 = new Tablet();
        medicine1.cure();
        medicine1.dosage();
        medicine1.store();
        medicine1.manufacture();
        medicine1.expiryDate();
        Tablet tablet = new Tablet();
        tablet.cure();
        tablet.dosage();
        tablet.store();
        tablet.manufacture();
        tablet.expiryDate();
        System.out.println("64================================");
        Appliance appliance = new Appliance();
        appliance.turnOn();
        appliance.turnOff();
        appliance.consumeElectricity();
        appliance.maintain();
        appliance.warrantyPeriod();
        Appliance appliance1 = new WashingMachine();
        appliance1.turnOn();
        appliance1.turnOff();
        appliance1.consumeElectricity();
        appliance1.maintain();
        appliance1.warrantyPeriod();
        WashingMachine washingMachine = new WashingMachine();
        washingMachine.turnOn();
        washingMachine.turnOff();
        washingMachine.consumeElectricity();
        washingMachine.maintain();
        washingMachine.warrantyPeriod();
        System.out.println("65===========================");
        School school = new School();
        school.study();
        school.exam();
        school.play();
        school.lunchBreak();
        school.teacherMeeting();
        School school1 = new Student();
        school1.study();
        school1.exam();
        school1.play();
        school1.lunchBreak();
        school1.teacherMeeting();
        Student student = new Student();
        student.study();
        student.exam();
        student.play();
        student.lunchBreak();
        student.teacherMeeting();
        System.out.println("66===========================");
        Hospital hospital = new Hospital();
        hospital.admitPatient();
        hospital.dischargePatient();
        hospital.treatPatient();
        hospital.manageStaff();
        hospital.maintainRecords();
        Hospital hospital1 = new Doctor();
        hospital1.admitPatient();
        hospital1.dischargePatient();
        hospital1.treatPatient();
        hospital1.manageStaff();
        hospital1.maintainRecords();
        Doctor doctor = new Doctor();
        doctor.admitPatient();
        doctor.dischargePatient();
        doctor.treatPatient();
        doctor.manageStaff();
        doctor.maintainRecords();
        System.out.println("67==================================");
        Restaurant restaurant = new Restaurant();
        restaurant.takeOrder();
        restaurant.serveFood();
        restaurant.prepareBill();
        restaurant.cleanTables();
        restaurant.manageStaff();
        Restaurant restaurant1 = new Chef();
        restaurant1.takeOrder();
        restaurant1.serveFood();
        restaurant1.prepareBill();
        restaurant1.cleanTables();
        restaurant1.manageStaff();
        Chef chef = new Chef();
        chef.takeOrder();
        chef.serveFood();
        chef.prepareBill();
        chef.cleanTables();
        chef.manageStaff();
        System.out.println("68====================================");
        Book book = new Book();
        book.read();
        book.bookmark();
        book.close();
        book.lend();
        book.store();
        Book book1 = new Novel();
        book1.read();
        book1.bookmark();
        book1.close();
        book1.lend();
        book1.store();
        Novel novel = new Novel();
        novel.read();
        novel.bookmark();
        novel.close();
        novel.lend();
        novel.store();
        System.out.println("69=======================================");
        Game game = new Game();
        game.play();
        game.pause();
        game.restart();
        game.quit();
        game.saveProgress();
        Game game1 = new Chess();
        game1.play();
        game1.pause();
        game1.restart();
        game1.quit();
        game1.saveProgress();
        Chess chess = new Chess();
        chess.play();
        chess.pause();
        chess.restart();
        chess.quit();
        chess.saveProgress();
        System.out.println("70===================================");
        Beverage beverage = new Beverage();
        beverage.prepare();
        beverage.serve();
        beverage.addSugar();
        beverage.stir();
        beverage.drink();
        Beverage beverage1 = new Tea();
        beverage1.prepare();
        beverage1.serve();
        beverage1.addSugar();
        beverage1.stir();
        beverage1.drink();
        Tea tea = new Tea();
        tea.prepare();
        tea.serve();
        tea.addSugar();
        tea.stir();
        tea.drink();
        System.out.println("71======================================");
        Plant plant = new Plant();
        plant.grow();
        plant.absorbSunlight();
        plant.photosynthesize();
        plant.reproduce();
        plant.consumeWater();
        Plant plant1 = new Tree();
        plant1.grow();
        plant1.absorbSunlight();
        plant1.photosynthesize();
        plant1.reproduce();
        plant1.consumeWater();
        Tree tree = new Tree();
        tree.grow();
        tree.absorbSunlight();
        tree.photosynthesize();
        tree.reproduce();
        tree.consumeWater();
        System.out.println("72===============================================");
        Tool tool = new Tool();
        tool.use();
        tool.maintain();
        tool.store();
        tool.clean();
        tool.repair();
        Tool tool1 = new Hammer();
        tool1.use();
        tool1.maintain();
        tool1.store();
        tool1.clean();
        tool1.repair();
        Hammer hammer = new Hammer();
        hammer.use();
        hammer.maintain();
        hammer.store();
        hammer.clean();
        hammer.repair();
        System.out.println("73=====================================================");
        Software software = new Software();
        software.install();
        software.run();
        software.update();
        software.uninstall();
        software.configure();
        Software software1 = new OperatingSystem();
        software1.install();
        software1.run();
        software1.update();
        software1.uninstall();
        software1.configure();
        OperatingSystem os = new OperatingSystem();
        os.install();
        os.run();
        os.update();
        os.uninstall();
        os.configure();
        System.out.println("74=====================================");
        Music music = new Music();
        music.play();
        music.pause();
        music.stop();
        music.adjustVolume();
        music.download();
        Music music1 = new Song();
        music1.play();
        music1.pause();
        music1.stop();
        music1.adjustVolume();
        music1.download();
        Song song = new Song();
        song.play();
        song.pause();
        song.stop();
        song.adjustVolume();
        song.download();
        System.out.println("75=====================================");
        Card card = new Card();
        card.swipe();
        card.insert();
        card.tap();
        card.validate();
        card.expire();
        Card card1 = new CreditCard();
        card1.swipe();
        card1.insert();
        card1.tap();
        card1.validate();
        card1.expire();
        CreditCard creditCard = new CreditCard();
        creditCard.swipe();
        creditCard.insert();
        creditCard.tap();
        creditCard.validate();
        creditCard.expire();
        System.out.println("76========================================");
        Airplane airplane = new Airplane();
        airplane.takeOff();
        airplane.fly();
        airplane.land();
        airplane.fuelCapacity();
        airplane.passengers();
        Airplane airplane1 = new Jet();
        airplane1.takeOff();
        airplane1.fly();
        airplane1.land();
        airplane1.fuelCapacity();
        airplane1.passengers();
        Jet jet = new Jet();
        jet.takeOff();
        jet.fly();
        jet.land();
        jet.fuelCapacity();
        jet.passengers();
        System.out.println("77========================================");
        Room room = new Room();
        room.openDoor();
        room.closeDoor();
        room.clean();
        room.ventilate();
        room.occupy();
        Room room1 = new Bathroom();
        room1.openDoor();
        room1.closeDoor();
        room1.clean();
        room1.ventilate();
        Bathroom bathroom = new Bathroom();
        bathroom.openDoor();
        bathroom.closeDoor();
        bathroom.clean();
        bathroom.ventilate();
        bathroom.occupy();
        System.out.println("78=================================");
        Country country = new Country();
        country.continent();
        country.population();
        country.government();
        country.currency();
        country.language();
        Country country1 = new India();
        country1.continent();
        country1.population();
        country1.government();
        country1.currency();
        country1.language();
        India india = new India();
        india.continent();
        india.population();
        india.government();
        india.currency();
        india.language();
        System.out.println("79=================================");
        Minister minister = new Minister();
        minister.makePolicies();
        minister.implementLaws();
        minister.attendMeetings();
        minister.representGovernment();
        minister.manageDepartment();
        Minister minister1 = new ChiefMinister();
        minister1.makePolicies();
        minister1.implementLaws();
        minister1.attendMeetings();
        minister1.representGovernment();
        minister1.manageDepartment();
        ChiefMinister cm = new ChiefMinister();
        cm.makePolicies();
        cm.implementLaws();
        cm.attendMeetings();
        cm.representGovernment();
        cm.manageDepartment();
        System.out.println("80===================================");
        Drop drop = new Drop();
        drop.liquidType();
        drop.volume();
        drop.use();
        drop.absorption();
        drop.dispense();
        Drop drop1 = new EyeDrop();
        drop1.liquidType();
        drop1.volume();
        drop1.use();
        drop1.absorption();
        drop1.dispense();
        EyeDrop eyeDrop = new EyeDrop();
        eyeDrop.liquidType();
        eyeDrop.volume();
        eyeDrop.use();
        eyeDrop.absorption();
        eyeDrop.dispense();
        System.out.println("81=============================");
        Port port = new Port();
        port.connect();
        port.transferData();
        port.supplyPower();
        port.type();
        Port port1 = new USB();
        port1.connect();
        port1.transferData();
        port1.supplyPower();
        port1.type();
        port1.compatibility();
        USB usb = new USB();
        usb.connect();
        usb.transferData();
        usb.supplyPower();
        usb.type();
        usb.compatibility();
        System.out.println("82===========================");
        Display display = new Display();
        display.showImage();
        display.resolution();
        display.refreshRate();
        display.brightness();
        display.displayType();
        Display display1 = new Monitor();
        display1.showImage();
        display1.resolution();
        display1.refreshRate();
        display1.brightness();
        display1.displayType();
        Monitor monitor = new Monitor();
        monitor.showImage();
        monitor.resolution();
        monitor.refreshRate();
        monitor.brightness();
        monitor.displayType();
        System.out.println("83=======================");
        Cycle cycle = new Cycle();
        cycle.pedal();
        cycle.brake();
        cycle.wheels();
        cycle.ringBell();
        cycle.stand();
        Cycle cycle1 = new Motorcycle();
        cycle1.pedal();
        cycle1.brake();
        cycle1.wheels();
        cycle1.ringBell();
        cycle1.stand();
        Motorcycle motorcycle = new Motorcycle();
        motorcycle.pedal();
        motorcycle.brake();
        motorcycle.wheels();
        motorcycle.ringBell();
        motorcycle.stand();
        System.out.println("84==========================");
        Oil oil = new Oil();
        oil.extract();
        oil.store();
        oil.cook();
        oil.viscosity();
        oil.use();
        Oil oil1 = new CoconutOil();
        oil1.extract();
        oil1.store();
        oil1.cook();
        oil1.viscosity();
        oil1.use();
        CoconutOil coconutOil = new CoconutOil();
        coconutOil.extract();
        coconutOil.store();
        coconutOil.cook();
        coconutOil.viscosity();
        coconutOil.use();
        System.out.println("85==============================");
        Door door = new Door();
        door.open();
        door.close();
        door.lock();
        door.unlock();
        door.material();
        Door door1 = new WoodenDoor();
        door1.open();
        door1.close();
        door1.lock();
        door1.unlock();
        door1.material();
        WoodenDoor woodenDoor = new WoodenDoor();
        woodenDoor.open();
        woodenDoor.close();
        woodenDoor.lock();
        woodenDoor.unlock();
        woodenDoor.material();
        System.out.println("86==================================");
        Light light = new Light();
        light.turnOn();
        light.turnOff();
        light.brightness();
        light.color();
        light.powerSource();
        Light light1 = new TubeLight();
        light1.turnOn();
        light1.turnOff();
        light1.brightness();
        light1.color();
        light1.powerSource();
        TubeLight tubeLight = new TubeLight();
        tubeLight.turnOn();
        tubeLight.turnOff();
        tubeLight.brightness();
        tubeLight.color();
        tubeLight.powerSource();
        System.out.println("87===================================================");
        Wire wire = new Wire();
        wire.conductElectricity();
        wire.insulation();
        wire.flexibility();
        wire.length();
        wire.usage();
        Wire wire1 = new CopperWire();
        wire1.conductElectricity();
        wire1.insulation();
        wire1.flexibility();
        wire1.length();
        wire1.usage();
        CopperWire copperWire = new CopperWire();
        copperWire.conductElectricity();
        copperWire.insulation();
        copperWire.flexibility();
        copperWire.length();
        copperWire.usage();
        System.out.println("88==================================");
        Person person = new Person();
        person.eat();
        person.sleep();
        person.walk();
        person.talk();
        person.breathe();
        Person person1 = new Professor();
        person1.eat();
        person1.sleep();
        person1.walk();
        person1.talk();
        person1.breathe();
        Professor professor = new Professor();
        professor.eat();
        professor.sleep();
        professor.walk();
        professor.talk();
        professor.breathe();
        System.out.println("89===============================================");
        Team team = new Team();
        team.play();
        team.train();
        team.compete();
        team.strategize();
        team.celebrate();
        Team team1 = new RCB();
        team1.play();
        team1.train();
        team1.compete();
        team1.strategize();
        team1.celebrate();
        RCB rcb = new RCB();
        rcb.play();
        rcb.train();
        rcb.compete();
        rcb.strategize();
        rcb.celebrate();
        System.out.println("90===================================================");
        ColdDrink coldDrink = new ColdDrink();
        coldDrink.drink();
        coldDrink.chill();
        coldDrink.flavor();
        coldDrink.fizz();
        coldDrink.sugarContent();
        ColdDrink coldDrink1 = new Sprite();
        coldDrink1.drink();
        coldDrink1.chill();
        coldDrink1.flavor();
        coldDrink1.fizz();
        coldDrink1.sugarContent();
        Sprite sprite = new Sprite();
        sprite.drink();
        sprite.chill();
        sprite.flavor();
        sprite.fizz();
        sprite.sugarContent();
        System.out.println("91=================================================");
        Organ organ = new Organ();
        organ.function();
        organ.bloodSupply();
        organ.regulation();
        organ.growth();
        organ.repair();
        Organ organ1 = new Heart();
        organ1.function();
        organ1.bloodSupply();
        organ1.regulation();
        organ1.growth();
        organ1.repair();
        Heart heart = new Heart();
        heart.function();
        heart.bloodSupply();
        heart.regulation();
        heart.growth();
        heart.repair();
        System.out.println("92====================================================");
        Tournament tournament = new Tournament();
        tournament.organize();
        tournament.teamsParticipate();
        tournament.scheduleMatches();
        tournament.declareWinner();
        Tournament tournament1 = new IPL();
        tournament1.organize();
        tournament1.teamsParticipate();
        tournament1.scheduleMatches();
        tournament1.declareWinner();
        tournament1.entertainFans();
        IPL ipl = new IPL();
        ipl.organize();
        ipl.teamsParticipate();
        ipl.scheduleMatches();
        ipl.declareWinner();
        ipl.entertainFans();
        System.out.println("93=========================================================");
        SportsEquipment equipment = new SportsEquipment();
        equipment.use();
        equipment.durability();
        equipment.brand();
        equipment.maintenance();
        equipment.cost();
        SportsEquipment equipment1 = new Bat();
        equipment1.use();
        equipment1.durability();
        equipment1.brand();
        equipment1.maintenance();
        equipment1.cost();
        Bat bat = new Bat();
        bat.use();
        bat.durability();
        bat.brand();
        bat.maintenance();
        bat.cost();
        System.out.println("94====================================================================");
        Money money = new Money();
        money.exchange();
        money.value();
        money.store();
        money.transfer();
        money.buyGoods();
        Money money1 = new Currency();
        money1.exchange();
        money1.value();
        money1.store();
        money1.transfer();
        money1.buyGoods();
        Currency currency = new Currency();
        currency.exchange();
        currency.value();
        currency.store();
        currency.transfer();
        currency.buyGoods();
        System.out.println("95==========================================================");
        Box box = new Box();
        box.storeItems();
        box.open();
        box.close();
        box.material();
        box.size();
        Box box1 = new MatchBox();
        box1.storeItems();
        box1.open();
        box1.close();
        box1.material();
        box1.size();
        MatchBox matchBox = new MatchBox();
        matchBox.storeItems();
        matchBox.open();
        matchBox.close();
        matchBox.material();
        matchBox.size();
        System.out.println("96============================================================");
        Coal coal = new Coal();
        coal.burn();
        coal.generateEnergy();
        coal.carbonContent();
        coal.extraction();
        coal.usage();
        Coal coal1 = new Charcoal();
        coal1.burn();
        coal1.generateEnergy();
        coal1.carbonContent();
        coal1.extraction();
        coal1.usage();
        Charcoal charcoal = new Charcoal();
        charcoal.burn();
        charcoal.generateEnergy();
        charcoal.carbonContent();
        charcoal.extraction();
        charcoal.usage();
        System.out.println("97=============================================================");
        Browser browser = new Browser();
        browser.open();
        browser.close();
        browser.navigate();
        browser.incognitoMode();
        browser.extensions();
        Browser browser1 = new Chrome();
        browser1.open();
        browser1.close();
        browser1.navigate();
        browser1.incognitoMode();
        browser1.extensions();
        Chrome chrome = new Chrome();
        chrome.open();
        chrome.close();
        chrome.navigate();
        chrome.incognitoMode();
        chrome.extensions();
        System.out.println("98===============================================");
        Clock clock = new Clock();
        clock.showTime();
        clock.setAlarm();
        clock.tick();
        clock.displayFormat();
        clock.powerSource();
        Clock clock1 = new Watch();
        clock1.showTime();
        clock1.setAlarm();
        clock1.tick();
        clock1.displayFormat();
        clock1.powerSource();
        Watch watch = new Watch();
        watch.showTime();
        watch.setAlarm();
        watch.tick();
        watch.displayFormat();
        watch.powerSource();
        System.out.println("99=================================================");
        Element element = new Element();
        element.existInNature();
        element.combineWithOtherElements();
        element.hasAtomicStructure();
        element.classifiedByType();
        element.periodicTablePresence();
        Element element1 = new Fire();
        element1.existInNature();
        element1.combineWithOtherElements();
        element1.hasAtomicStructure();
        element1.classifiedByType();
        element1.periodicTablePresence();
        Fire fire = new Fire();
        fire.existInNature();
        fire.combineWithOtherElements();
        fire.hasAtomicStructure();
        fire.classifiedByType();
        fire.periodicTablePresence();
        System.out.println("100============================================================");
        Skill skill = new Skill();
        skill.learn();
        skill.improve();
        skill.apply();
        skill.requiresEffort();
        skill.hasLevels();
        Skill skill1 = new Karate();
        skill1.learn();
        skill1.improve();
        skill1.apply();
        skill1.requiresEffort();
        skill1.hasLevels();
        Karate karate = new Karate();
        karate.learn();
        karate.improve();
        karate.apply();
        karate.requiresEffort();
        karate.hasLevels();


    }
}
